server:
  tomcat:
    cookie-processor: org.apache.tomcat.util.http.LegacyCookieProcessor
  port: 8080
  servlet:
    context-path: /practiceApp

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 60m
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/practiceApp
    username: postgres
    password: qwerty
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
dump:
  pg_dump:
    program:
      path: D:/Programs/PostgreSQL/16/bin/